#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate web/report-assets.js from analyze_and_report.py.

The report renderer (its HTML shell, CSS and JS) lives in ONE place — the Python file. The
browser build imports the very same strings instead of keeping a second copy that would drift.

    python3 build_web.py          # writes web/report-assets.js
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import analyze_and_report as A                                     # noqa: E402

OUT = os.path.join(HERE, 'web', 'report-assets.js')

banner = ('// GENERATED by build_web.py from analyze_and_report.py — do not edit by hand.\n'
          '// The report shell, styles and behaviour have exactly one source: the Python file.\n')

body = (banner +
        'export const REPORT_HTML = ' + json.dumps(A.HTML) + ';\n' +
        'export const REPORT_JS = ' + json.dumps(A.JS) + ';\n' +
        'export const REPORT_SEARCH = ' + json.dumps(A.SEARCH) + ';\n\n' +
        '''// One standalone report document — the same bytes the Python CLI writes.
export function buildReport(data) {
  const body = REPORT_HTML
    .replace('__DATA__', JSON.stringify(data).replace(/</g, '\\\\u003c'))
    .replace('__JS__', REPORT_JS)
    .replace('__SEARCH__', REPORT_SEARCH);
  return '<!doctype html><html lang="en"><head><meta charset="utf-8">'
    + '<meta name="viewport" content="width=device-width,initial-scale=1">'
    + '<title>Claude Code session report \\u2014 ' + (data.meta.session || '') + '</title></head><body>'
    + body + '</body></html>';
}
''')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w', encoding='utf-8').write(body)
print('wrote %s (%.0f KB)' % (OUT, len(body) / 1024))
